"$schema" = "./node_modules/wrangler/config-schema.json"

name = "2026-mayfest"
compatibility_date = "2026-05-12"
route = "ap-mayfest.com/2026/*"

[assets]
directory = "./out"
not_found_handling = "single-page-application"
